[FIX] web: handle typeerror during domain validation
Currently, an error occurs when user tries to validate a domain with no field
name.

Steps to install:
- Install `sale_management` > Open sale order list view > Turn on debug mode.
- Click on search bar > Custom filter > Click on the field and remove its field name
  written below the list of fields.
- Click validate.

Error:
```
TypeError: Empty field name in condition ('', '=', 1)
```

Cause:
- As the field name was emptied by the user the [line] will raise a TypeError
  during the domain validation.
- Till `19.0` any error during domain validation was handled  through [here]
  which was later changed to handle only ValueErrors through this [commit].

Solution:
- Handled TypeErrors during domain validation.

[line]: https://github.com/odoo/odoo/blob/260b9c0417ed2278429fcdd7f50d61786d4e9beb/odoo/orm/domains.py#L841

[here]: https://github.com/odoo/odoo/blob/a220fb71c036c93fa1e75d4d37127e5eda0118f9/addons/web/controllers/domain.py#L34

[commit]: https://github.com/odoo/odoo/commit/a1434c32e9f4dd226d512677fd96e3051b908d8b#diff-e5da86414a8020b2843fb359453238e4977027d30f73f1fa792ca63ddd8fa2a7L34-R23

sentry-7278978488

closes odoo/odoo#250820

X-original-commit: 52b19c21633e03c990825dc778200196451838b8
Signed-off-by: Julien Castiaux (juc) <juc@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>